
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8084/eureka/
#    instance:
#      hostname: hostname
spring:
  application:
    name: zuul
  redis:
    database: 9
    host: 39.105.115.232
    jedis:
      max-active: 600
      max-idle: 300
      max-wait: 1000
      min-idle: 50
    timeout: 10000
    password: CW-password
    port: 6379
zuul:
  routes:
    myproject:
      path: /web/**
      serviceId: web
server:
  port: 8082
  #-/**/
