spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bbs
    username: root
    password: 123456
  jackson:
    time-zone: GMT+8
  mail:
    host: smtp.163.com
    username: pandapanzhu@163.com
    password: ZSlaoyao1
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
