server:
  port: 8084
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8084/eureka/
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false
  instance:
    hostname: eureka
spring:
  application:
    name: eureka
